In [1]:
import pandas as pd
fac = pd.read_csv('Facilities_Database.csv')

In [3]:
fac['facdomain'] = fac['facdomain'].astype('category')

In [4]:
fac['facdomain_cat']=fac['facdomain'].cat.codes

In [8]:
fac.facdomain_cat.dtypes

dtype('int8')

In [10]:
import numpy as np

In [33]:
pd.pivot_table(fac, index=['nta'], columns=['facdomain_cat'],values= 'count')

KeyError: 'count'

In [14]:
fac[['nta','facdomain_cat']].groupby('nta').agg(['count'])

     facdomain_cat
             count
nta
BK09           177
BK17           141
BK19           114
BK21           176
BK23            49
...            ...
SI37           169
SI45            66
SI48            27
SI54            79
SI99             1

[195 rows x 1 columns]

In [22]:
onehot = fac[['nta','facdomain']]

In [23]:
one_hot = pd.get_dummies(onehot['facdomain'])

In [24]:
onehot = onehot.join(one_hot)

In [26]:
onehot= onehot.drop('facdomain',axis=1)

In [35]:
onehot.groupby('nta').sum()

,ADMINISTRATION OF GOVERNMENT,CORE INFRASTRUCTURE AND TRANSPORTATION,"EDUCATION, CHILD WELFARE, AND YOUTH",HEALTH AND HUMAN SERVICES,LIBRARIES AND CULTURAL PROGRAMS,"PARKS, GARDENS, AND HISTORICAL SITES","PUBLIC SAFETY, EMERGENCY SERVICES, AND ADMINISTRATION OF JUSTICE"
nta,,,,,,,
BK09,23.0,16.0,54.0,44.0,15.0,22.0,3.0
BK17,14.0,14.0,74.0,22.0,7.0,9.0,1.0
BK19,2.0,5.0,63.0,32.0,4.0,6.0,2.0
BK21,27.0,20.0,62.0,39.0,8.0,18.0,2.0
BK23,3.0,9.0,22.0,8.0,2.0,3.0,2.0
...,...,...,...,...,...,...,...
SI37,28.0,14.0,48.0,51.0,7.0,19.0,2.0
SI45,19.0,2.0,33.0,5.0,1.0,5.0,1.0
SI48,11.0,1.0,9.0,0.0,0.0,6.0,0.0
SI54,28.0,4.0,29.0,7.0,3.0,7.0,1.0
SI99,1.0,0.0,0.0,0.0,0.0,0.0,0.0